### ISSUE TITLE
Strange error 'onHeartbeat' failed 'KeyError'.

### ISSUE THREAD

**Issue by AdamWeglarz** [Smanar/Domoticz-deCONZ#8]
Hi,

In log I see something worrying:
"
2019-01-25 18:37:11.289 Error: (Deconz zigbee) 'onHeartbeat' failed 'KeyError'.
2019-01-25 18:37:11.289 Error: (Deconz zigbee) ----> Line 722 in /home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py, function onHeartbeat
2019-01-25 18:37:11.289 Error: (Deconz zigbee) ----> Line 337 in /home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py, function onHeartbeat
"

Any idea why?

Adam

**Comment by Smanar** [comment]
Lol, hi again, firstly, I m rly sorry for you, and your daily bug with my plugin.
Next, you have this bug because you have Parameters["Mode2"] that don't exist. But it can't be possible.

It s created on line 29 in plugin.py, you haven't edited this line ?

Try adding this code in the onstart() part
```
        for x in Parameters:
            if Parameters[x] != "":
                Domoticz.Log( "'" + x + "':'" + str(Parameters[x]) + "'")
```
You will have something like this in log
```
 2019-01-25 19:49:35.169 (deCONZ) 'DomoticzHash':'a3a45906'
2019-01-25 19:49:35.169 (deCONZ) 'Address':'127.0.0.1'
2019-01-25 19:49:35.169 (deCONZ) 'Mode2':'36E138295E'
2019-01-25 19:49:35.169 (deCONZ) 'Mode1':'8088'
2019-01-25 19:49:35.169 (deCONZ) 'DomoticzVersion':'4.9700'
2019-01-25 19:49:35.169 (deCONZ) 'Version':'1.0.1'
2019-01-25 19:49:35.169 (deCONZ) 'Port':'80'
2019-01-25 19:49:35.169 (deCONZ) 'Author':'Smanar'
2019-01-25 19:49:35.169 (deCONZ) 'HomeFolder':'/home/pi/domoticz/plugins/deCONZ/'
2019-01-25 19:49:35.169 (deCONZ) 'Key':'deCONZ'
2019-01-25 19:49:35.169 (deCONZ) 'Mode3':'2'
2019-01-25 19:49:35.169 (deCONZ) 'DomoticzBuildTime':'2018-06-23 16:24:51'
2019-01-25 19:49:35.169 (deCONZ) 'Name':'deCONZ'
2019-01-25 19:49:35.169 (deCONZ) 'HardwareID':'2' 
```

**Comment by AdamWeglarz** [comment]
No it is after some time!
Restart fixes it. And it come backes.
[smoke3.txt](https://github.com/Smanar/Domoticz-deCONZ/files/2797528/smoke3.txt)
I attach full log with errors :)

Adam

**Comment by Smanar** [comment]
I m searching on domoticz forum how the dictionnary Parameters can be currupted.

BTW I have a question for you.
You have too this error
```
2019-01-24 16:33:51.242  Error: (Deconz zigbee) PyDomoticz_Error failed to parse parameters: string expected.
2019-01-24 16:33:51.242  Error: (Deconz zigbee) 'PyDomoticz_Error' failed 'ValueError'.
2019-01-24 16:33:51.242  Error: (Deconz zigbee) 'onMessage' failed 'SystemError'.
2019-01-24 16:33:51.242  Error: (Deconz zigbee) ----> Line 706 in /home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py, function onMessage
2019-01-24 16:33:51.242  Error: (Deconz zigbee) ----> Line 203 in /home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py, function onMessage
```

I m on it ATM, and it's perhaps an unicode problem with special character, have you the previous line with communication log enabled, something like this

```
2019-01-18 08:58:03.024 (deCONZ) Processing 'ReadEvent' message
2019-01-18 08:58:03.024 (deCONZ) Received 159 bytes of data
2019-01-18 08:58:03.024 (deCONZ) 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 41 63 63 HTTP/1.1.200.OK..Acc
2019-01-18 08:58:03.024 (deCONZ) 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d 41 6c 6c 6f 77 2d 4f 72 ess-Control-Allow-Or
2019-01-18 08:58:03.025 (deCONZ) 69 67 69 6e 3a 20 2a 0d 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 igin:.*..Content-Typ
2019-01-18 08:58:03.025 (deCONZ) 65 3a 20 61 70 70 6c 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 3b e:.application/json;
2019-01-18 08:58:03.025 (deCONZ) 20 63 68 61 72 73 65 74 3d 75 74 66 2d 38 0d 0a 43 6f 6e 74 .charset=utf-8..Cont
2019-01-18 08:58:03.025 (deCONZ) 65 6e 74 2d 4c 65 6e 67 74 68 3a 32 0d 0a 45 54 61 67 3a 22 ent-Length:2..ETag:"
2019-01-18 08:58:03.025 (deCONZ) 36 36 32 39 65 66 31 30 61 62 38 34 30 30 34 64 34 31 39 30 6629ef10ab84004d4190
2019-01-18 08:58:03.025 (deCONZ) 31 34 34 65 39 31 30 30 34 63 63 37 22 0d 0a 0d 0a 7b 7d .. 144e91004cc7"....{}
```

**Comment by Smanar** [comment]
Which one domoticz version are you using ?

**Comment by Smanar** [comment]
Which one domoticz version are you using ?
Wich one python versions ?

I have done a special version to test https://github.com/Smanar/Domoticz-deCONZ/tree/beta
It will not solve your problem, but I hope will give more information, you can set the debug log to "python only"

Edit:
For information the second bug is corrected now, this one with 
`'onMessage' failed 'SystemError'.`

Some news about your problem ?

**Comment by dobber81** [comment]
I have something similar in my log:

2019-04-03 11:55:40.573 Error: (deCONZ) 'onMessage' failed 'KeyError'.
2019-04-03 11:55:40.573 Error: (deCONZ) ----> Line 783 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onMessage
2019-04-03 11:55:40.573 Error: (deCONZ) ----> Line 276 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onMessage
2019-04-03 11:55:40.573 Error: (deCONZ) ----> Line 634 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function WebSocketConnexion

Looks like port 8088 is correct for socket and I can control connected lights. I have tried checking the box for accespting new devices, but same error is displayed in log.

Domoticz version 4.10597
Deconz version: deconz-2.05.60-qt5.deb
Plugin version: latest from beta git. 2019-04-02

**Comment by Smanar** [comment]
I m on it ATM.
It's because this device miss a model filed
line 634 
`model = self.Devices[IEEE]['model']`
became 
`model = self.Devices[IEEE].get('model','')`

I think you have just added a device in deconz without restarting the plugin.
You can just try to restart the plugin : hardware/select decos/update

I m on it ATM, I will correct the beta this night, but I have some problem ATM with the vibration sensor.

**Comment by dobber81** [comment]
I did it that way a few times, but error still occured. A total restart of the Pi mode the problem go away for a while, but then returned. I will try the new beta a see if it gets any better.

**Comment by Smanar** [comment]
Np ^^
Tell me if it's better with the last beta pls.
Logically you can't have the bug again because if the field model is empty, with the modification it will be "" instaed of provoking a keyerror.

**Comment by dobber81** [comment]
Latest dom beta git:
2019-04-04 08:20:02.798 Error: (deCONZ) 'onMessage' failed 'KeyError'.
2019-04-04 08:20:02.798 Error: (deCONZ) ----> Line 791 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onMessage
2019-04-04 08:20:02.798 Error: (deCONZ) ----> Line 277 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function onMessage
2019-04-04 08:20:02.798 Error: (deCONZ) ----> Line 641 in '/home/pi/domoticz/plugins/Domoticz-deCONZ/plugin.py', function WebSocketConnexion

Automatic lights off from domoticz. Lights turned off, but got error in log. Restarted the entire Pi after updating last night. Does not matter which of my 10 bulbs I power on or off, same message appears. Mostly Ikea Trådfri, but also some Innr and Osram lights.

**Comment by Smanar** [comment]
Ok, so can you send me the websocket data just before the bug pls ?

`IEEE = str(_Data.get('uniqueid',self.GetDeviceIEEE(_Data['id'],_Data['r'])))`

I m using the 'uniqueid' field, in your case I m sure you don't have it, that is normal it can occur.
So I m using to the ID and the type to search in the plugin database, and it don't work on your situation.
It can bug if you have a banned device.

Try using this modification
```
        IEEE = str(_Data.get('uniqueid',self.GetDeviceIEEE(_Data['id'],_Data['r'])))
        if IEEE == 'banned':
            Domoticz.Log("Banned device > " + str(_Data['id']) + ' (' + str(_Data['r']) + ')')
            return
        if not IEEE:
            Domoticz.Error("Websocket error, unknow device > " + str(_Data['id']) + ' (' + str(_Data['r']) + ')')
            return
        model = self.Devices[IEEE].get('model','')
```

you have the first line (641) and the last line (642)

**Comment by Smanar** [comment]
Hu, sorry, I don't find the problem
Can you send me the first line when you restart the plugin
```
2019-04-04 19:02:29.423 (deCONZ) ### Request Groups
2019-04-04 19:02:29.527 (deCONZ) Classic Data : {'4': {'devicemembership': [], 'lights': ['3', '8'], 'action': {'bri': 127, 'xy': [0, 0], 'on': True, 'sat': 127, 'scene': None, 'hue': 0, 'colormode': 'ct', 'effect': 'none', 'ct': 535}, 'etag': '910e0b2ad71de0fea2c8f68842ea834f', 'name': 'Couloir', 'state': {'any_on': True, 'all_on': True}, 'id': '4', 'scenes': [], 'type': 'LightGroup'}, '3': {'devicemembership': [], 'lights': [], 'action': {'bri': 127, 'xy': [0, 0], 'on': False, 'sat': 127, 'scene': None, 'hue': 0, 'colormode': 'hs', 'effect': 'none', 'ct': 0}, 'etag': 'd94648f8cbbb85637e40c0dee548437f', 'name': 'test', 'state': {'any_on': False, 'all_on': False}, 'id': '3', 'scenes': [], 'type': 'LightGroup'}, '7805': {'devicemembership': ['2'], 'lights': [], 'action': {'bri': 127, 'xy': [0, 0], 'on': False, 'sat': 127, 'scene': None, 'hue': 0, 'colormode': 'hs', 'effect': 'none', 'ct': 0}, 'etag': 'd94648f8cbbb85637e40c0dee548437f', 'name': 'TRADFRI remote control 2', 'state': {'any_on': False, 'all_on': False}, 'id': '7805', 'scenes': [], 'type': 'LightGroup'}}
2019-04-04 19:02:29.527 (deCONZ) ### Groupe > 4 Name:Couloir
2019-04-04 19:02:29.527 (deCONZ) ### Groupe > 3 Name:test
2019-04-04 19:02:29.527 (deCONZ) ### Groupe > 7805 Name:TRADFRI remote control 2 
```

I see only 2 possibles bug.
In the JSON the id is not the same
The data are not stored in the plugin database.

**Comment by dobber81** [comment]
2019-04-04 19:14:44.058 (deCONZ) Protocol for 'deCONZ_WebSocket' not specified, 'None' assumed.
2019-04-04 19:14:44.058 (deCONZ) Transport set to: 'TCP/IP', 10.0.0.19:8088.
2019-04-04 19:14:44.058 (deCONZ) Connect directive received, action initiated successfully.
2019-04-04 19:14:44.109 (deCONZ) onConnect called
2019-04-04 19:14:44.109 (deCONZ) Sending 308 bytes of data
2019-04-04 19:14:44.159 (deCONZ) Received 349 bytes of data
2019-04-04 19:14:44.159 (deCONZ) onMessage called
2019-04-04 19:14:44.159 (deCONZ) Websocket Http data : HTTP/1.1 101 Switching Protocols
***Upgrade: websocket
***Connection: Upgrade
***Sec-WebSocket-Accept: V0htEbn5FhIA1xfQRyG3yU1aG9c=
***Server: deconz
***Access-Control-Allow-Credentials: false
***Access-Control-Allow-Methods: GET
***Access-Control-Allow-Headers: content-type
***Access-Control-Allow-Origin: http://10.0.0.15
***Date: Thu, 04 Apr 2019 17:14:44 GMT
***
***
2019-04-04 19:14:44.021 Status: (deCONZ) Initialized version 1.0.6, author 'Smanar'
2019-04-04 19:14:44.021 Status: (deCONZ) Entering work loop.
2019-04-04 19:14:44.109 Status: (deCONZ) Launching websocket on port 8088
2019-04-04 19:14:45.040 (RFLink) Wind (Vindmätare)
2019-04-04 19:14:48.808 (Z-Wave) General/kWh (HTPC kWh)
2019-04-04 19:14:49.657 (Z-Wave) General/kWh (HTPC kWh)
2019-04-04 19:14:54.204 (deCONZ) ### Device > 4 Name:Spotlight Höger Type:Dimmable light Details:{'reachable': True, 'bri': 25, 'on': False, 'alert': 'none'}
2019-04-04 19:14:54.205 (deCONZ) ### Update device (Spotlight Höger) : {'sValue': 'Off', 'nValue': 0}, IGNORED , no changes !
2019-04-04 19:14:54.205 (deCONZ) ### Device > 8 Name:Vardagsrum Fram Type:Dimmable light Details:{'reachable': True, 'bri': 198, 'on': True, 'alert': 'none'}
2019-04-04 19:14:54.206 (deCONZ) ### Update device (Vardagsrum Fram) : {'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.224 (deCONZ) ### Device > 3 Name:Spotlight Vänster Type:Dimmable light Details:{'reachable': True, 'bri': 228, 'on': False, 'alert': 'none'}
2019-04-04 19:14:54.225 (deCONZ) ### Update device (Spotlight Vänster) : {'sValue': 'Off', 'nValue': 0}, IGNORED , no changes !
2019-04-04 19:14:54.225 (deCONZ) ### Device > 9 Name:Vitrinskåp Type:On/Off plug-in unit Details:{'reachable': True, 'on': True, 'alert': 'none'}
2019-04-04 19:14:54.225 (deCONZ) ### Update device (Vitrinskåp) : {'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.242 (deCONZ) ### Device > 2 Name:Datarum Type:Dimmable light Details:{'reachable': True, 'bri': 76, 'on': False, 'alert': 'none'}
2019-04-04 19:14:54.243 (deCONZ) ### Update device (Datarum) : {'sValue': 'Off', 'nValue': 0}, IGNORED , no changes !
2019-04-04 19:14:54.243 (deCONZ) ### Device > 11 Name:Vardagsrum Uppe Type:Dimmable light Details:{'reachable': True, 'bri': 152, 'on': True, 'alert': 'none'}
2019-04-04 19:14:54.243 (deCONZ) ### Update device (Vardagsrum Uppe) : {'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.250 (deCONZ) ### Device > 6 Name:Matrum Type:Extended color light Details:{'reachable': True, 'hue': 65426, 'sat': 254, 'effect': 'none', 'colormode': 'ct', 'xy': [0.44593, 0.406714], 'bri': 226, 'on': True, 'ct': 351, 'alert': 'none'}
2019-04-04 19:14:54.251 (deCONZ) ### Update device (Matrum) : {'sValue': 'Off', 'Color': '{"ct":193,"t":0,"ww":0}', 'nValue': 0}
2019-04-04 19:14:54.259 (deCONZ) ### Device > 13 Name:Trappa Type:Color temperature light Details:{'reachable': True, 'colormode': 'xy', 'bri': 64, 'on': True, 'ct': 349, 'alert': 'none'}
2019-04-04 19:14:54.260 (deCONZ) ### Update device (Trappa) : {'sValue': 'Off', 'Color': '{"ct":193,"t":0,"ww":0}', 'nValue': 0}
2019-04-04 19:14:54.272 (deCONZ) ### Device > 12 Name:Fönster Uppe Type:Extended color light Details:{'reachable': True, 'hue': 42240, 'sat': 254, 'effect': 'none', 'colormode': 'xy', 'xy': [0.1355, 0.0398718], 'bri': 114, 'on': True, 'ct': 323, 'alert': 'none'}
2019-04-04 19:14:54.273 (deCONZ) ### Update device (Fönster Uppe) : {'sValue': 'Off', 'Color': '{"ct":180,"t":0,"ww":0}', 'nValue': 0}
2019-04-04 19:14:54.286 (deCONZ) ### Device > 5 Name:Spotlight Mitten Type:Dimmable light Details:{'reachable': True, 'bri': 251, 'on': False, 'alert': 'none'}
2019-04-04 19:14:54.287 (deCONZ) ### Update device (Spotlight Mitten) : {'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.298 (deCONZ) ### Device > 10 Name:Vardagsrum Bak Type:Dimmable light Details:{'reachable': True, 'bri': 198, 'on': True, 'alert': 'none'}
2019-04-04 19:14:54.299 (deCONZ) ### Update device (Vardagsrum Bak) : {'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.306 (deCONZ) ### Device > 7 Name:Matbord Type:Color temperature light Details:{'reachable': True, 'colormode': 'xy', 'bri': 229, 'on': False, 'ct': 332, 'alert': 'none'}
2019-04-04 19:14:54.306 (deCONZ) ### Update device (Matbord) : {'sValue': 'Off', 'Color': '{"ct":185,"t":0,"ww":0}', 'nValue': 0}
2019-04-04 19:14:54.314 (deCONZ) ### Request sensors
2019-04-04 19:14:54.314 (deCONZ) Send Command /api/2DF295010C/sensors/ with None
2019-04-04 19:14:54.314 (deCONZ) Disconnect directive received for '10.0.0.19:80'.
2019-04-04 19:14:54.314 (deCONZ) Handling TCP disconnect, socket (10.0.0.19:80) is connected
2019-04-04 19:14:54.315 (deCONZ) Queued asyncronous read aborted (10.0.0.19:80).
2019-04-04 19:14:54.365 (deCONZ) Disconnect event received for '10.0.0.19:80'.
2019-04-04 19:14:54.367 (deCONZ) Deallocating connection object 'deCONZ_Com' (10.0.0.19:80).
2019-04-04 19:14:54.367 (deCONZ) Protocol for 'deCONZ_Com' not specified, 'None' assumed.
2019-04-04 19:14:54.367 (deCONZ) Transport set to: 'TCP/IP', 10.0.0.19:80.
2019-04-04 19:14:54.367 (deCONZ) Connect directive received, action initiated successfully.
2019-04-04 19:14:54.420 (deCONZ) onConnect called
2019-04-04 19:14:54.421 (deCONZ) Sending 184 bytes of data
2019-04-04 19:14:54.490 (deCONZ) Received 2896 bytes of data
2019-04-04 19:14:54.491 (deCONZ) Received 568 bytes of data
2019-04-04 19:14:54.491 (deCONZ) onMessage called
2019-04-04 19:14:54.491 (deCONZ) Incomplete trame, miss 568 bytes
2019-04-04 19:14:54.491 (deCONZ) onMessage called
2019-04-04 19:14:54.495 (deCONZ) Classic Data : {'1': {'manufacturername': 'Philips', 'config': {'configured': True, 'sunriseoffset': 30, 'on': True, 'sunsetoffset': -30}, 'type': 'Daylight', 'name': 'Daylight', 'swversion': '1.0', 'etag': '0e57ef3e09d2b41dfbe4bd99578b63bf', 'modelid': 'PHDL00', 'state': {'lastupdated': '2019-03-30T00:08:29', 'status': 100, 'dark': True, 'daylight': False}, 'uniqueid': '00:21:2e:ff:ff:02:79:71-01'}, '4': {'manufacturername': 'IKEA of Sweden', 'config': {'battery': 60, 'reachable': True, 'on': True, 'group': '25405', 'alert': 'none'}, 'type': 'ZHASwitch', 'uniqueid': '90:fd:9f:ff:fe:d7:71:5a-01-1000', 'mode': 3, 'name': 'TRÅDFRI remote control', 'swversion': '1.2.214', 'etag': '0f641535f08e4e128cf7e5052a700d71', 'modelid': 'TRADFRI remote control', 'state': {'lastupdated': '2019-04-04T15:34:57', 'buttonevent': 1002}, 'ep': 1}, '8': {'manufacturername': 'LUMI', 'config': {'battery': 100, 'reachable': True, 'on': True, 'temperature': 2100}, 'type': 'ZHASwitch', 'uniqueid': '00:15:8d:00:01:04:20:1f-03-000c', 'mode': 1, 'name': 'Xiaomi Cube', 'swversion': '20160407', 'etag': '5267d1939307feeeff18e3439947ef3b', 'modelid': 'lumi.sensor_cube', 'state': {'lastupdated': '2019-04-02T20:59:21', 'buttonevent': -1019}, 'ep': 3}, '5': {'manufacturername': 'Phoscon', 'config': {'reachable': True, 'on': True}, 'type': 'CLIPGenericFlag', 'name': 'CLIP-Sensor TOOGLE-ON-OFF', 'swversion': '1.0', 'etag': '2a26ea54ded35f686458edcaef7842c0', 'modelid': 'PHOSCON_FSM_FLAG', 'state': {'lastupdated': '2019-03-30T00:08:29', 'flag': False}, 'uniqueid': '90:fd:9f:ff:fe:d7:71:5a-01-1000-toogle-on-off'}, '10': {'manufacturername': 'Phoscon', 'config': {'reachable': True, 'on': True}, 'type': 'CLIPGenericFlag', 'name': 'CLIP-Sensor TOOGLE-ON-OFF', 'swversion': '1.0', 'etag': 'fc8454473b61fd16c4c80db69bb7e74d', 'modelid': 'PHOSCON_FSM_FLAG', 'state': {'lastupdated': '2019-04-02T19:16:46', 'flag': False}, 'uniqueid': '00:0b:57:ff:fe:a5:0f:de-01-1000-toogle-on-off'}, '9': {'manufacturername': 'IKEA of Sweden', 'config': {'battery': 60, 'reachable': True, 'on': True, 'group': '23501', 'alert': 'none'}, 'type': 'ZHASwitch', 'uniqueid': '00:0b:57:ff:fe:a5:0f:de-01-1000', 'mode': 3, 'name': 'Trappa', 'swversion': '1.2.214', 'etag': '5464ebfd1e0f539c13cff7749c84378a', 'modelid': 'TRADFRI remote control', 'state': {'lastupdated': '2019-04-02T19:17:04', 'buttonevent': 3003}, 'ep': 1}, '7': {'manufacturername': 'LUMI', 'config': {'battery': 100, 'reachable': True, 'on': True, 'temperature': 2100}, 'type': 'ZHASwitch', 'uniqueid': '00:15:8d:00:01:04:20:1f-02-0012', 'mode': 1, 'name': 'Xiaomi Cube', 'swversion': '20160407', 'etag': 'e8085ad600158b8bb67c027a8360328b', 'modelid': 'lumi.sensor_cube', 'state': {'lastupdated': '2019-04-04T15:38:45', 'buttonevent': 7007}, 'ep': 2}, '6': {'manufacturername': 'IKEA of Sweden', 'config': {'battery': 100, 'reachable': True, 'on': True, 'group': '44335', 'alert': 'none'}, 'type': 'ZHASwitch', 'uniqueid': '00:0b:57:ff:fe:2c:82:f2-01-1000', 'mode': 4, 'name': 'Spotlights', 'swversion': '1.2.248', 'etag': 'cfe3ba72fed340099df37ae220a83fe0', 'modelid': 'TRADFRI wireless dimmer', 'state': {'lastupdated': 'none', 'buttonevent': None}, 'ep': 1}, '2': {'manufacturername': 'IKEA of Sweden', 'config': {'battery': 47, 'reachable': True, 'on': True, 'group': '2', 'alert': 'none'}, 'type': 'ZHASwitch', 'uniqueid': '00:0d:6f:ff:fe:9b:d0:f9-01-1000', 'mode': 1, 'name': 'Datarum', 'swversion': '2.0.020', 'etag': 'c46f1136aa968016aefea67e4f66eb81', 'modelid': 'TRADFRI on/off switch', 'state': {'lastupdated': '2019-04-03T20:40:08', 'buttonevent': 2002}, 'ep': 1}}
2019-04-04 19:14:54.495 (deCONZ) ### Device > 1 Name:Daylight Type:Daylight Details:{'lastupdated': '2019-03-30T00:08:29', 'status': 100, 'dark': True, 'daylight': False}
2019-04-04 19:14:54.496 (deCONZ) Skipping Device (Banned) : 00:21:2e:ff:ff:02:79:71-01
2019-04-04 19:14:54.496 (deCONZ) ### Device > 4 Name:TRÅDFRI remote control Type:ZHASwitch Details:{'lastupdated': '2019-04-04T15:34:57', 'buttonevent': 1002}
2019-04-04 19:14:54.496 (deCONZ) Skipping Device (Banned) : 90:fd:9f:ff:fe:d7:71:5a-01-1000
2019-04-04 19:14:54.496 (deCONZ) ### Device > 8 Name:Xiaomi Cube Type:ZHASwitch Details:{'lastupdated': '2019-04-02T20:59:21', 'buttonevent': -1019}
2019-04-04 19:14:54.496 (deCONZ) ### Update device (Mi Cube Rotation) : {'BatteryLevel': 100, 'sValue': 'Off', 'nValue': 0}, IGNORED , no changes !
2019-04-04 19:14:54.496 (deCONZ) ### Device > 5 Name:CLIP-Sensor TOOGLE-ON-OFF Type:CLIPGenericFlag Details:{'lastupdated': '2019-03-30T00:08:29', 'flag': False}
2019-04-04 19:14:54.496 (deCONZ) Skipping Device (Banned) : 90:fd:9f:ff:fe:d7:71:5a-01-1000-toogle-on-off
2019-04-04 19:14:54.496 (deCONZ) ### Device > 10 Name:CLIP-Sensor TOOGLE-ON-OFF Type:CLIPGenericFlag Details:{'lastupdated': '2019-04-02T19:16:46', 'flag': False}
2019-04-04 19:14:54.497 (deCONZ) Skipping Device (Banned) : 00:0b:57:ff:fe:a5:0f:de-01-1000-toogle-on-off
2019-04-04 19:14:54.497 (deCONZ) ### Device > 9 Name:Trappa Type:ZHASwitch Details:{'lastupdated': '2019-04-02T19:17:04', 'buttonevent': 3003}
2019-04-04 19:14:54.497 (deCONZ) Skipping Device (Banned) : 00:0b:57:ff:fe:a5:0f:de-01-1000
2019-04-04 19:14:54.497 (deCONZ) ### Device > 7 Name:Xiaomi Cube Type:ZHASwitch Details:{'lastupdated': '2019-04-04T15:38:45', 'buttonevent': 7007}
2019-04-04 19:14:54.497 (deCONZ) ### Update device (Mi Cube) : {'BatteryLevel': 100, 'sValue': 'Off', 'nValue': 0}
2019-04-04 19:14:54.503 (deCONZ) ### Device > 6 Name:Spotlights Type:ZHASwitch Details:{'lastupdated': 'none', 'buttonevent': None}
2019-04-04 19:14:54.503 (deCONZ) Skipping Device (Banned) : 00:0b:57:ff:fe:2c:82:f2-01-1000
2019-04-04 19:14:54.503 (deCONZ) ### Device > 2 Name:Datarum Type:ZHASwitch Details:{'lastupdated': '2019-04-03T20:40:08', 'buttonevent': 2002}
2019-04-04 19:14:54.503 (deCONZ) Skipping Device (Banned) : 00:0d:6f:ff:fe:9b:d0:f9-01-1000
2019-04-04 19:14:54.503 (deCONZ) ### Request Groups
2019-04-04 19:14:54.503 (deCONZ) Send Command /api/2DF295010C/groups/ with None
2019-04-04 19:14:54.504 (deCONZ) Disconnect directive received for '10.0.0.19:80'.
2019-04-04 19:14:54.504 (deCONZ) Handling TCP disconnect, socket (10.0.0.19:80) is connected
2019-04-04 19:14:54.504 (deCONZ) Queued asyncronous read aborted (10.0.0.19:80).
2019-04-04 19:14:54.554 (deCONZ) Disconnect event received for '10.0.0.19:80'.
2019-04-04 19:14:54.558 (deCONZ) Deallocating connection object 'deCONZ_Com' (10.0.0.19:80).
2019-04-04 19:14:54.559 (deCONZ) Protocol for 'deCONZ_Com' not specified, 'None' assumed.
2019-04-04 19:14:54.559 (deCONZ) Transport set to: 'TCP/IP', 10.0.0.19:80.
2019-04-04 19:14:54.559 (deCONZ) Connect directive received, action initiated successfully.
2019-04-04 19:14:54.610 (deCONZ) onConnect called
2019-04-04 19:14:54.610 (deCONZ) Sending 183 bytes of data
2019-04-04 19:14:54.660 (deCONZ) Received 1448 bytes of data
2019-04-04 19:14:54.660 (deCONZ) Received 1581 bytes of data
2019-04-04 19:14:54.660 (deCONZ) onMessage called
2019-04-04 19:14:54.660 (deCONZ) Incomplete trame, miss 1581 bytes
2019-04-04 19:14:54.660 (deCONZ) onMessage called
2019-04-04 19:14:54.666 (deCONZ) Classic Data : {'5': {'name': 'Trappa', 'lights': ['13'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'ct', 'xy': [0, 0], 'bri': 127, 'on': True, 'ct': 0}, 'devicemembership': [], 'etag': '49cbe90a99a6fe392674b67776f0f9d1', 'id': '5', 'state': {'all_on': True, 'any_on': True}}, '1': {'name': 'Vardagsrum', 'lights': ['1', '3', '5', '4', '8', '10'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': [], 'etag': 'aef2603dbce6d6ea1f6e86c644214e4d', 'id': '1', 'state': {'all_on': False, 'any_on': True}}, '4': {'name': 'Matrum', 'lights': ['6', '7', '9'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 65176, 'sat': 250, 'effect': 'none', 'colormode': 'xy', 'xy': [0.730755, 0.264424], 'bri': 127, 'on': True, 'ct': 0}, 'devicemembership': [], 'etag': '1312ca23f67f06f4a49e5965e840a808', 'id': '4', 'state': {'all_on': False, 'any_on': True}}, '23501': {'name': 'TRADFRI remote control 9', 'lights': ['13'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': ['9'], 'etag': '49cbe90a99a6fe392674b67776f0f9d1', 'id': '23501', 'state': {'all_on': True, 'any_on': True}}, '3': {'name': 'Datarum', 'lights': ['2'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': [], 'etag': 'eed9605bf3e432fca82d2ea52e4d43e0', 'id': '3', 'state': {'all_on': False, 'any_on': False}}, '44335': {'name': 'TRADFRI wireless dimmer 6', 'lights': ['3', '5', '4'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': ['6'], 'etag': 'c26a8d3b07f160a43f889fd5c369f382', 'id': '44335', 'state': {'all_on': False, 'any_on': False}}, '6': {'name': 'Övervåning', 'lights': ['11', '12'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 102, 'on': True, 'ct': 0}, 'devicemembership': [], 'etag': '40e2402894c7b0c081ed5f8c6047baf7', 'id': '6', 'state': {'all_on': True, 'any_on': True}}, '25405': {'name': 'TRADFRI remote control 4', 'lights': ['7'], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': ['4'], 'etag': '1312ca23f67f06f4a49e5965e840a808', 'id': '25405', 'state': {'all_on': False, 'any_on': False}}, '2': {'name': 'TRADFRI on/off switch ', 'lights': [], 'type': 'LightGroup', 'scenes': [], 'action': {'scene': None, 'hue': 0, 'sat': 127, 'effect': 'none', 'colormode': 'hs', 'xy': [0, 0], 'bri': 127, 'on': False, 'ct': 0}, 'devicemembership': ['2'], 'etag': '5f87ee1f4bc0437f01d70e25f44fcb35', 'id': '2', 'state': {'all_on': False, 'any_on': False}, 'uniqueid': '00:0d:6f:ff:fe:9b:d0:f9'}}
2019-04-04 19:14:54.666 (deCONZ) ### Groupe > 5 Name:Trappa
2019-04-04 19:14:54.666 (deCONZ) Skipping Group (Banned) : GROUP_Trappa
2019-04-04 19:14:54.666 (deCONZ) ### Groupe > 1 Name:Vardagsrum
2019-04-04 19:14:54.666 (deCONZ) Skipping Group (Banned) : GROUP_Vardagsrum
2019-04-04 19:14:54.666 (deCONZ) ### Groupe > 4 Name:Matrum
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_Matrum
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 23501 Name:TRADFRI remote control 9
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_TRADFRI_remote_control_9
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 3 Name:Datarum
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_Datarum
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 44335 Name:TRADFRI wireless dimmer 6
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_TRADFRI_wireless_dimmer_6
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 6 Name:Övervåning
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_Övervåning
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 25405 Name:TRADFRI remote control 4
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_TRADFRI_remote_control_4
2019-04-04 19:14:54.667 (deCONZ) ### Groupe > 2 Name:TRADFRI on/off switch
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_TRADFRI_on/off_switch_
2019-04-04 19:14:54.667 (deCONZ) Disconnect directive received for '10.0.0.19:80'.
2019-04-04 19:14:54.667 (deCONZ) Handling TCP disconnect, socket (10.0.0.19:80) is connected
2019-04-04 19:14:54.668 (deCONZ) Queued asyncronous read aborted (10.0.0.19:80).
2019-04-04 19:14:54.718 (deCONZ) Disconnect event received for '10.0.0.19:80'.
2019-04-04 19:14:54.667 Status: (deCONZ) ### deCONZ ready
2019-04-04 19:14:54.667 Status: (deCONZ) ### Found 13 Operators, 9 Sensors, 9 Groups and 0 others, with 16 Ignored

**Comment by Smanar** [comment]
Ok ^^, it' that
```
2019-04-04 19:14:54.666 (deCONZ) ### Groupe > 4 Name:Matrum
2019-04-04 19:14:54.667 (deCONZ) Skipping Group (Banned) : GROUP_Matrum
```

So you can try the previous modification

```
        IEEE = str(_Data.get('uniqueid',self.GetDeviceIEEE(_Data['id'],_Data['r'])))
        if IEEE == 'banned':
            Domoticz.Log("Banned device > " + str(_Data['id']) + ' (' + str(_Data['r']) + ')')
            return
        if not IEEE:
            Domoticz.Error("Websocket error, unknow device > " + str(_Data['id']) + ' (' + str(_Data['r']) + ')')
            return
        model = self.Devices[IEEE].get('model','')
```

you have the first line (641) and the last line (642)

But it's normal all your group are banned ?

**Comment by dobber81** [comment]
I will try the code a bit later tonight.
I dont use the groups from deconz because I rather group the lights in domoticz instead. I have a bunch of wifi yeelights and z-wave switches that I also control within the domoticz groups.
When I have the groups disabled I dont have to see them in domoticz. I have enough other devices to keep track of :)

**Comment by Smanar** [comment]
We can make group in domoticz ? with scenario ?

But if you don't use deconz group, you are not forced to put all your buld in a group, you can keep it alone, or you make group for remote ?

**Comment by dobber81** [comment]
Sorry, I forgot to mention that. Yes I do use groups for remotes in deconz. And for the occational use of phoscon gui when domoticz is out of order for one reason or another. I just dont need them in domoticz where I use the built in scenario/group.

**Comment by dobber81** [comment]
I think that piece of code made it better!

2019-04-04 20:51:53.617 (deCONZ) onCommand called for Unit 17: Parameter 'Off', Level: 0, Hue:
2019-04-04 20:51:53.736 (deCONZ) Banned device > 9 (sensors)
2019-04-04 20:51:53.609 Status: User: dobber initiated a switch command (1752/Vitrinskåp/Off)

No red error text anymore.

When doing this testing I noticed another strange behavior. When I press update on the hardware page to restart the plugin all the connected lights status in domoticz is set to off. It does not update the light status from deconz when plugin starts up. When I turne a light on or off in deconz the status is updated in domoticz, just not the first time when the plugin i restarted. It this normal?

**Comment by Smanar** [comment]
I have changed this part from "log" to "debug", like that you will not have your logs filled in 10mn.

And no, was not normal, was because the field "alert", I have just remove it, you will not have this bug again in the actual version.

Thx for "bug hunting" ^^.

**Comment by dobber81** [comment]
Thank you for a great plugin!

I'll let you know if I notice any other strange behavior.
